### ISSUE TITLE
add bogachenko list

### ISSUE THREAD

**Issue by KonoromiHimaries** [hl2guide/All-in-One-Customized-Adblock-List#16]
https://github.com/bogachenko/presstheattack/blob/master/presstheattack.txt

**Comment by hl2guide** [comment]
Thanks, I've added this to the testing list for the next version.

**Comment by bogachenko** [comment]
wow

**Comment by hl2guide** [comment]
I've decided to let that list mature before I include it in AIO. _I may be including it half a year from now, if it is stable._

**Comment by bogachenko** [comment]
I renamed the repository, your script needs updating
REPO: https://github.com/bogachenko/filterlist/
RAW: https://raw.githubusercontent.com/bogachenko/filterlist/master/filterlist.txt
