### ISSUE TITLE
whitlisted

### ISSUE THREAD

**Issue by unknowtech** [hl2guide/All-in-One-Customized-Adblock-List#18]
@@||wwwd.caf.fr/icfstatiquesangularappli^$important

@@||leboncoin.fr/ad-small^$important
@@||lleboncoin.fr/ad-thumb^$important
@@||leboncoin.fr/ad-large^$important
@@||leboncoin.fr/ad-image^$important

@@||static.mytf1.tf1.fr/assets/js/build/lib/gigya.js?bust=205$important

@@||cdns.gigya.com/js^$important

@@||cdns.eu1.gigya.com/gs/webSdk^$important

@@||static.mytf1.tf1.fr/assets/js/build/lib/lazyload.js?bust=205$important

thank

**Comment by hl2guide** [comment]
Since this AIO list is opt-in, I'll not white-list sites I'm unaware of or can't test for malware or other issues.
