### ISSUE TITLE
Remove Youtube Filters

### ISSUE THREAD

**Issue by elmagow** [hl2guide/All-in-One-Customized-Adblock-List#19]
Hello,

How do I remove the youtube filters from the list?
Not the ads, just the things that remove comment, suggestions and sidebar

Regards

**Comment by hl2guide** [comment]
For the upcoming version 2.3 I'm considering adding optional variants (subject to change).
One of the variants would be one that does not remove Youtube comments, suggestions and sidebar.
Stay tuned 💃

**Comment by hl2guide** [comment]
Real-world commitments in my life are putting off the creation of variants.
Once it settles down I'll try to get it into version 2.4.

**Comment by hl2guide** [comment]
Please try out the beta for variants and let me know, in your adblocker simply add:
https://raw.githubusercontent.com/hl2guide/All-in-One-Customized-Adblock-List/master/VARIANTS%20(Beta)/Beta-AIO-YT-Excluded-Variant.txt
