### ISSUE TITLE
Archived Official News #1

### ISSUE THREAD

**Issue by hl2guide** [hl2guide/All-in-One-Customized-Adblock-List#2]
### **FOR THE LATEST NEWS, SCROLL TO THE BOTTOM OF THIS PAGE**

**The lists I've currently disabled are:**
- AFNIL - Anti Fake News International List (new tab issue)
- NoTrack (login issue)
- Web Annoyances Ultralist (looping issue)
- I Don't Care about Cookies (website is down)

I'm currently running the update script every 1 hour 40 minutes as a scheduled task on a older laptop.

Please comment below if you notice updates not appearing.

**Comment by hl2guide** [comment]
Windows 10 updating at a weird time caused the update outage today, sorry.

**Comment by yourduskquibbles** [comment]
@hl2guide I'm the maintainer of the [Web Annoyances Ultralist](https://github.com/yourduskquibbles/webannoyances), can you describe what the looping issue is that you referenced, wondering if it is something I can fix on my end.

**Comment by hl2guide** [comment]
The July update for Windows 10 caused issues with the list generator. Should be fixed now!

**Comment by hl2guide** [comment]
I'm currently testing the Google CAPTCHA and LastPass drop menu conflicts.

**Comment by hl2guide** [comment]
I'm internally testing version 2.1 of the list. Version 2.1 is about 1 week away, if all goes to plan 💃

**Comment by hl2guide** [comment]
Version 2.1 is out! 👯

**Comment by hl2guide** [comment]
Version 2.2 is in alpha, privately testing more lists and clean up 👯

**Comment by hl2guide** [comment]
Version 2.2 is in private alpha 2, going well so far.
Expected full public release around the end of October 2018.

**Comment by hl2guide** [comment]
Version 2.2 is out 🎆

**Comment by hl2guide** [comment]
Version 2.3 should come out early next year (end of Jan - Middle of Feb).

**Comment by hl2guide** [comment]
My low-powered laptop stopped being reliable, so I'm now generating the AIO List on a far more powerful PC. Should help a bit with consistency for updates 😸

**Comment by hl2guide** [comment]
For November updates for the list have been rocky to say the least.

_So I'll try to monitor it more over December and then take steps to improve consistency in the New Year._

**Comment by hl2guide** [comment]
I've moved from my spotty PowerShell-based task scheduler to Windows' Task Scheduler with a custom task.

So far so good since it seems to use 1/4 the memory, runs only at interval (while generating) and should be more reliable. I'll monitor this over December and evaluate the results 🍡
