### ISSUE TITLE
Jan 2019 Refresh Clean up

### ISSUE THREAD

**Issue by hl2guide** [hl2guide/All-in-One-Customized-Adblock-List#28]
I've completed an audit of the rule usage of the AIO list, e.g.

![example audit usage of rules](https://user-images.githubusercontent.com/17044982/51783338-36cc2f80-218c-11e9-909f-593944548a1c.jpg)

I disabled 3 lists: 

- https://easylist-downloads.adblockplus.org/malwaredomains_full.txt
- http://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&mimetype=plaintext
- AdGuard Base filter​ (English)

**Comment by bogachenko** [comment]
Is your computer alive?

**Comment by hl2guide** [comment]
lol, the laptop is chugging along.
It's dealing with the Australian summer.
FYI:
![fyi](https://user-images.githubusercontent.com/17044982/51784712-60dc1c80-21a1-11e9-8ef9-abc56e26c94a.png)

**Comment by bogachenko** [comment]
@hl2guide I have 8, but even I will not risk setting up so many lists. I take care of my prehistoric dinosaur-computer

![default](https://user-images.githubusercontent.com/8535285/51784756-d9ad8b00-2145-11e9-98ad-f9047279101a.png)
