### ISSUE TITLE
consider removing Fanboy Annoyances list or whitelisting gravityrd-services.com

### ISSUE THREAD

**Issue by torzsmokus** [hl2guide/All-in-One-Customized-Adblock-List#29]
This domain is used for loading in-site recommendations and search results from Yusp by Gravity R&D on many sites around the web. I consider it an error to block the whole domain altogether, as it degrades the normal operation (e.g. predictive search) of certain sites.
My [request to Fanboy to remove the domain from their list](https://github.com/easylist/easylist/pull/1341) was turned down.

**Comment by hl2guide** [comment]
I agree with Fanboy's stance on this. I suggest you manually whitelist gravityrd-services.com.
