### ISSUE TITLE
please abandon the official support for adblockplus

### ISSUE THREAD

**Issue by KonoromiHimaries** [hl2guide/All-in-One-Customized-Adblock-List#3]
- many filter lists for your included does not support adblock plus
- 155.000 rules unusable this filter at the adblock plus
( ram less & more laggss.. + potentially broken many sites )

https://github.com/hl2guide/All-in-One-Customized-Adblock-List/wiki

**Comment by hl2guide** [comment]
I'll consider this but I have not noticed any more RAM usage or more lags that you mention.
