### ISSUE TITLE
2.7 - Gmail Fixes

### ISSUE THREAD

**Issue by CaptainFrosty** [hl2guide/All-in-One-Customized-Adblock-List#35]
Hi, your DOM settings are breaking Gmail. I have to disable cosmetic filtering in uBlock Origin to get the center box to display the emails.

**Comment by hl2guide** [comment]
I'll do some testing to confirm this. Thanks for reporting it.

**Comment by hl2guide** [comment]
I've confirmed this is valid. I suggest you disable adblock for the moment for Gmail, since there's not much difference. I'll track down the actual filter and get a fix in a future version.

**Comment by hl2guide** [comment]
Version 2.7 is under testing in private alpha 3.
