### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by bogachenko** [hl2guide/All-in-One-Customized-Adblock-List#39]
Hi, why aren't you posting your script, (yes, I know that it's probably simple), but still

**Comment by hl2guide** [comment]
It's a custom PowerShell script that downloads the lists. I worry about the repercussions from releasing it as it could make a lot of lists unavailable from people spamming download/bandwidth.

As a result I've only made the generated AIO list open source.

**Comment by bogachenko** [comment]
It would be cool to see everything. I think so

**Comment by bogachenko** [comment]
You should think about it.
