### ISSUE TITLE
Unbreaking CNN videos

### ISSUE THREAD

**Issue by CaptainFrosty** [hl2guide/All-in-One-Customized-Adblock-List#41]
Whitelisting https://fave.api.cnn.io will unbreak CNN videos

**Comment by CaptainFrosty** [comment]
Also I see there are already some Wall Street Journal fixes but I had to add https://wsjstream.wsj.net and https://video-api.wsj.com to get those playing again

**Comment by hl2guide** [comment]
This list is aggressive and comprehensive, for websites that you want to use on the regular I suggest you add the site to the exceptions.

**Comment by CaptainFrosty** [comment]
you know the list contains a lot of whitelisted elements right?
