### ISSUE TITLE
Filter List Suggestions

### ISSUE THREAD

**Issue by hl2guide** [hl2guide/All-in-One-Customized-Adblock-List#42]
If you find an awesome new adblock filter list that is not in the AIO list already, please suggest it below.

**Comment by CaptainFrosty** [comment]
https://www.squidblacklist.org/downloads/dg-malicious.acl

160,000+ unique entries

https://www.squidblacklist.org/downloads/dg-ads.acl

additional ads list

**Comment by jsEveryDay** [comment]
@hl2guide Great repo, love the list, hope this will stay alive for awhile. Every 2 hours may be an overkill.

Given the new Chrome 75 limits I was wondering if we could shrink down the list by limiting by continent, so making it a more english oriented user by adding only US, EU, CA, AU domains to the list.
Not sure if basing it on dns records would be enough. Trying to http resolve them isn't really a solution as they are Referer dependant. Also a lot of the lists referenced contain plenty of dead domains, so I guess you're already resolving them.
If you have any suggestions or experience on tackling this I will gladly write the code and maintain the list.

**Comment by hl2guide** [comment]
Google's nonsense on this is their own creation so, I'll take it into account. Since dead domains can be re-registered at any time I treat it as those domains still having a "bad reputation" rating and block by default.

2.8 will contain plenty of optimization and shrinking. But it's a while off until it comes out.
