### ISSUE TITLE
Github.com

### ISSUE THREAD

**Issue by jsEveryDay** [hl2guide/All-in-One-Customized-Adblock-List#46]
I thought this was just Adblocking .... not UI customizing. I guess it's not high screen res compatible
![image](https://user-images.githubusercontent.com/16431055/59968153-043c1e00-9503-11e9-970d-42a821a66092.png)

**Comment by hl2guide** [comment]
Thanks for reporting this, the upcoming 2.8 major update should resolve this issue completely.

**Comment by hl2guide** [comment]
This will be fixed in 2.8.
