### ISSUE TITLE
[suggestion] AdBlock/Hosts lists.

### ISSUE THREAD

**Issue by eladkarako** [hl2guide/All-in-One-Customized-Adblock-List#49]
https://github.com/eladkarako/hosts

<pre>
https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts0.txt

https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts0_with_localhost.txt

---------------------------------------------------------------------------------------------------

https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts_adblock.txt

https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts_adblock_anti_annoyances_hide.txt

https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts_adblock_anti_annoyances_block.txt

https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts_adblock_anti_annoyances_block_inline_script.txt

https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts_adblock_anti_annoyances_style_inject.txt
</pre>

**Comment by hl2guide** [comment]
Thanks for this suggestion.

I'm currently working on a project that offers a detailed tutorial and a consolidated, ordered and deduplicated hosts list for use in a DNS Sinkhole Server with an encrypted forwarder link.

Using this method should allow users to not use adblockers at all in browsers (a nice performance boost).
Or use them much more sparingly.

More development is needed on my end for this before I release it publicly. Any work will appear in my GitHub repos.
