### ISSUE TITLE
Google logo

### ISSUE THREAD

**Issue by CaptainFrosty** [hl2guide/All-in-One-Customized-Adblock-List#50]
Surely an exception is appropriate for the logo on the Google homepage. I mean really. Several exist for the autocomplete and a few other things. It's the regexes in "Satterly's Adblock Plus Filters" affecting Google stuff.

`@@||www.google.com/images/branding/googlelogo/*$image,domain=www.google.com`

**Comment by hl2guide** [comment]
ok, I'll look into it.
