### ISSUE TITLE
add ffa list

### ISSUE THREAD

**Issue by KonoromiHimaries** [hl2guide/All-in-One-Customized-Adblock-List#52]
```
https://github.com/bogachenko/fuckfuckadblock/blob/master/fuckfuckadblock.txt
```

**Comment by hl2guide** [comment]
Thanks @KonoromiHimaries , I'll consider it 💃

**Comment by llacb47** [comment]
That list has some problematic filters, I would not recommend adding the whole thing.

**Comment by KonoromiHimaries** [comment]
> That list has some problematic filters

report it here https://github.com/bogachenko/fuckfuckadblock/issues
