### ISSUE TITLE
add my list

### ISSUE THREAD

**Issue by xorcan** [hl2guide/All-in-One-Customized-Adblock-List#53]
https://github.com/xorcan/hosts/blob/master/README-EN.md

https://raw.githubusercontent.com/xorcan/hosts/master/xhosts.txt

_OnePlus 5 cihazımdan [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) kullanılarak iletildi._

**Comment by hl2guide** [comment]
Thanks @xorcan, I'll test that out.
