### ISSUE TITLE
cbs.com streaming

### ISSUE THREAD

**Issue by eldervamp** [hl2guide/All-in-One-Customized-Adblock-List#54]
I've checked for the past day and it seems that s0.2mdn.net, cdn3.optimizely.com, and imasdk.googleapis.com are preventing video streaming. Ublock filters has white-listed these for cbs.com but it seems there are entries in the All-In-One filters that are overriding them.

After going through the filter list. List 70 [Press the Attack], 76 [Skeletal Blocker], and 88 [Ublock Personal Filters] all have 

> ||2mdn.net^$important

> ||imasdk.googleapis.com^$important,redirect=noopframe,subdocument

> ||imasdk.googleapis.com^$important

 The ^$important entries which is why the white-lists entries are not working.

**Comment by hl2guide** [comment]
This list is aggressive, therefore there is going to be lot of overlap on the filters that take affect.

Everyone uses the internet in a different way and has their on favourite websites and websites they will never visit.

While I cannot test for each every (major) website in the world, I will try to alleviate this issue in version 2.8.
