### ISSUE TITLE
abc.go.com

### ISSUE THREAD

**Issue by eldervamp** [hl2guide/All-in-One-Customized-Adblock-List#55]
The past day imasdk.googleapis.com seems to be blocking video streaming. Ublock filter had white-listed this for abc.go.com but is seems the all-in-one list is overriding it. Unblocking imasdk.googleapis.com allows video streaming but now the stream / search bar is not visible.

Some relation to #54

**Comment by hl2guide** [comment]
I will try to solve this issue too in version 2.8.
