### ISSUE TITLE
Duplicates?

### ISSUE THREAD

**Issue by krystian3w** [hl2guide/All-in-One-Customized-Adblock-List#59]
> * Fanboy's Annoyance List (Fanboy) [Blocks Social Media content, in-page pop-ups and other annoyances.] - https://easylist.to/easylist/fanboy-annoyance.txt

> * Fanboy's Social Blocking List (Fanboy) [Blocks social media components.] - https://easylist-downloads.adblockplus.org/fanboy-social.txt

Fanboy Annoyance have embeded filters from `Fanboy's Social Blocking List` IMO no need wasting resources.

**Comment by hl2guide** [comment]
ok thanks, I'll look into this 💃
