### ISSUE TITLE
(not an issue): ABOUT PROJECT  DNS SINKHOLE

### ISSUE THREAD

**Issue by EstherMoellman** [hl2guide/All-in-One-Customized-Adblock-List#60]
Hi Dean @hl2guide !

Today I was reading about your fantastic "DNS-sinkhole-project"... and sounds great!
I am not an expert, but I am a member of a small club (150 university students in 8 different countries) with the hobby of using Firefox Nightly with lot of customizations-tweaks-hacks (CSS, Preferences, Add-ons etc). And I offer you our help to your project (we can do for you tests, researches etc).

The priority of our small club is browser performance.
We don't want privacy or security alternatives at the cost of browser performance.
And ad-tracker-etc-blockers are browser performance killers.

For a long time we tested alternatives avoiding blocker-add-ons/extensions.
Blockers at system level (at the OS out from the browser) didn't work too, because most of them use their own DNS, and the latency is a browser performance killer if you don't live near those DNS (not to mention privacy issues).

Windows hosts file, also is complicated.
As you know, it doesn't work with REGEXs or wildcards etc, so huge blocking lists are needed, and normally this hurts browser performance. After 50k items at hosts file, browsers start to feel the pain.

By the end, we left with two choices:

1) "NO-ADS" (http://www.schooner.com/~loverso/no-ads/):
This one is similar to your project, in the sense that tries to create a kind of local pi-hole.
It is old, but it still works like a charm. If you have not heard about it, then you may be interested.
We (our small club) customized "no-ads" adding more REGEXs and blocking-lists, and "no-ads" really worked nice. It still has some issues, but is a nice alternative from browser performance point of view.

2) "SIMPLEDNSCRYPT" (https://github.com/bitbeans/SimpleDnsCrypt):
As you know, this is not an ad-tracker-etc-blocker.
But it has a "black-list" area (also a "white-list" area etc)... and it works like a charm.
Technically, I have no idea why this is much better than Windows hosts. But I confirm you: The "black-list" can be full of items (more than 300k), and negative browser performance is imperceptible. My guess is that its cache is much bigger than Windows hosts cache.
Also as a plus, the "black-list" accepts wildcards! Amazing!
In brief, this one has been our choice, offering us at system level, an incredible ad-tracker-etc-blocking power, with very low negative browser impact (and the plus of DNS encryption).

If by chance is possible to merge your project with SimpleDNSCrypt... then it will be absolutely spectacular!
If somehow your project can take advantage of SimpleDNSCrypt' low browser performance impact... this will be a dream... the final ultimate unbeatable blocker.
What SimpleDNSCrypt needs to be the best blocker:
a) To work with REGEXs
b) To avoid loading ads, trackers etc working at request level (blocking requests)
c) To send garbage (requests) to a pi-hole, minimizing use of CPU, RAM etc

Well, that's all Dean, I just want to offer our help to your project, and also wanted to share with you our experience on this field.

Thank you in advance!

**Comment by hl2guide** [comment]
Seems like you're intentions are similar.

To be clear I'm not creating a new DNS Sinkhole Server software,
but using an existing one.

I'm currently testing: https://github.com/TechnitiumSoftware/DnsServer
with a custom whitelist and blacklist in development.

Related issue where I asked about wildcards:
https://github.com/TechnitiumSoftware/DnsServer/issues/59

I'm not sure if it supports regexs,
the developer seems very receptive to polite questions thought :D

My current early internal alpha has: 
80 Zones Allowed
4,714 Zones Blocked

The repo I'd launch would have:
- a detailed tutorial for setup and usage
- blacklist.txt file (includes blocked zones)
- whitelist.txt file

The technique I'm currently testing is to first block at zones at their base and
then secondly block bad/ad websites within permitted zones (e.g. .COM).

Some blocked zones for me are: .AAA, .AARP etc.

That way I have a smaller list and no needless entries (that are covered by a base zone).

I'm taking a hesitant approach and want to do far more testing before I
create a live repository.

The whitelist and blacklist files may well be applicable to SimpleDNSCrypt too.

Thanks for the offer of help, still early days so I need to work out the best approach first 🔍

**Comment by EstherMoellman** [comment]
... thanks @hl2guide for your answer... I wrote a message to the DnsServer' Dev (https://github.com/TechnitiumSoftware/DnsServer/issues/81)... and I really hope you will keep going ahead building the blocking lists etc, and building this new garbage-blocker. If we can help you, call us.

**Comment by hl2guide** [comment]
Hi,

I'd love to get your opinion on the current Alpha 2 of the blocklist at:
https://raw.githubusercontent.com/hl2guide/DNS-Sinkhole-Lists-A2/master/0_combined_blocklist.txt

Naturally it is ready for testing but not production ready. It weighs in at just under 2MB.
It requires using a DNS Sinkhole Server that supports blocking base zones.

**Comment by EstherMoellman** [comment]
@hl2guide ... COUNT ON ME! : )
It'll be my pleasure to test and to help whatever I can test/help. Please, I just have two simple requests:

1) I need a basic tutorial from your side, in order to optimize DnsServer' settings, exactly in the same way you plan to use it. I tested DnsServer but only with default settings. I have no idea how to deal with DnsServer' settings, nor with base zones, nor with etc. You don't need to loose time writing the perfect tutorial. Please, just write me some lines, in a raw way, describing step by step how you want me to install DnsServer, and how you want me to use your blocking list, blocking base zones, DnsServer' settings and whatever you believe will be important to set at Dnsserver in order to have a good testing of your project.

2) After your basic DnsServer' tutorial, I'll need at least one week, in order to test your list in a real-life test.

Thanks!

PS: If you can, please play a little with SimpleDNSCrypt (https://github.com/bitbeans/SimpleDnsCrypt). It is based on the famous DNSCrypt (https://dnscrypt.info/), which has a complete Wiki at https://github.com/jedisct1/dnscrypt-proxy/wiki.
Originally was made to work as he best DNS encryption. This is its main function. But it has many other functions, as for example "blocking stuff".
I am not an expert, and I don't know the technical difference between DNSCrypt VS DnsServer. Also, I don't know if DNSCrypt can work as a pi-hole. The DNSCrypt' Wiki seems to say DNSCrypt can do everything, but I confess you, it is behind my knowledge.
I used DNSCrypt for more than 2 years, and it worked like a charm. But I used in the simple way, just by adding a simple blocking list (a kind of Windows hosts file on steroids).
DNSCrypt works with wildcards, similar to DnsServer.
As I mentioned above, I couldn't optimize DnsServer' settings, so in my tests DNSCrypt went better than DnsServer (less RAM, less CPU, and browsing visibly faster). May be this will change after the basic DnsServer' tutorial I requested you.
But in any case, I believe it will interesting for you, to play a little with DNSCrypt, so you will have choices to decide which software you want for your blocking project.
Also, and you were right, DnsServer' Dev is very responsive, I we should include him in our comments, so who knows, if we found differences between DnsServer and DNSCrypt, perhaps he may make improvements at DnsServer. He already confirmed that will try to include REGEX at DnsServer.

**Comment by hl2guide** [comment]
Basic tutorial for testers only is attached as a PDF 👍 

Please note that the current combine blocklist does block social media websites (like Facebook) by default. I'm still considering a variant but I really consider social media sites as a security risk personally.

[Alpha 2 Tutorial.pdf](https://github.com/hl2guide/All-in-One-Customized-Adblock-List/files/3523217/Alpha.2.Tutorial.pdf)

**Comment by hl2guide** [comment]
From my personal testing of SimpleDnsCrypt it used more RAM, the interface was less intuitive and blocking of sites didn't work.
Also to my knowledge it also won't work on linux based distros (using .NET Core).

**Comment by EstherMoellman** [comment]
... @hl2guide thanks for the tutorial, I just opened/read it, haven't implemented it yet, but at first glance already seems a very nice tutorial, much more than I was expecting. Thanks again! Please give me a week, and I will return you back with my results. Around 50 users are going to participate in this test.

Just a question: Do you want me to test ads? Trackers? Malwares? Etc? Or everything?
Personally, and if you allow me an opinion, it will more efficient to test by stages, for example first-stage testing just ad-blocking, second-stage just trackers... and so on.

PS: With regards to DNSCrypt:

DNSCrypt is one thing, and SimpleDNSCrypt is another thing... and as its own name says, the latest is "Simple", it's meant to be "Simple", basic etc... therefore, we can't compare settings/options with DnsServer. We only can compare RAM, CPU, blocking functions etc.
Advanced users needing more options/settings, should directly use DNSCrypt, which allows tons of customizations by editing the DNSCrypt' files (no UI). For example, by editing DNSCrypt' files, you can perfectly automatize the use of blocking-lists in the form of links (uploading and updating the automatically). Everything is explained at the DNSCrypt' Wiki.  
But yeah, I agree with you, DNSCrypt is not "intuitive" as DnsServer (which from average users point of view will be better for your project). Yeah, when compared to DnsServer, DNSCrypt demands lot of previous reading (Wiki etc) before installing.

However and back to your tests, for sure something went wrong there, because:
- I have a 4MB blocking-list at SimpleDNSCrypt, and consumes me just 10% RAM compared to DnsServer
- Absolutely everything is blocked with SimpleDNSCrypt + my list
- The browsing speed is amazing compared to other blockers (including DnsServer)
- I use wildcards at my blocking-list, which allows me to cover thousand of alternatives just with few rules
- Etc

But please, let's forget DNSCrypt now, let's focus on your requested test and DnsServer. I will follow your tutorial and I will test your blocking-list + zones. And I will let you know if for me it goes better or not than DNSCrypt.

**Comment by hl2guide** [comment]
ok great, I think testing in stages will be wonderful.
Whatever methodology you feel comfortable with.

Nice to have outcomes would be:
- a list of domains that need to be added to the allowed list
- a list of tracker domains that aren't already blocked
- a list of potential domain lists (smaller than 1MB) that don't already appear on the repo

**Comment by EstherMoellman** [comment]
@hl2guide , the (around) 50 users participating in this test are from 8 different countries. Some of them now are informing me that "com.br" (Brazil) domains are totally blocked. Please, how can I allow "com.br" while keeping the ad-blocking capability?

**Comment by hl2guide** [comment]
Well, that's a problem. I didn't know the testers would be so international.

I'll need to create regional variants to achieve that functionality. I expected English speaking nations that would never ever request .br domains.

**Comment by EstherMoellman** [comment]
... I perfectly understand your approach, and many times I already saw this approach: blocking ".com.XX" where "XX" is never used, is an effective way to block lot of garbage. Sadly, as collateral effect, you lose international users. So by the end, this is going to be your call, if you decide to keep your project only for English speakers, then no needs for changes. But if you plan to open your project for everybody, then will need some adjustments.

The most important ads and trackers servers are international. So non English speakers perfectly can use your project if you just allow "com.XX" domains (or "YYY.XX" domains). But again, yeah, you're right, allowing "YYY.XX" domains opens the door to lot of potential garbage (including malwares), and as a consequence it demands larger and larger blocking-lists, more work, more RAM, more CPU, more etc... what can I say? It's your call. Perhaps, unfortunately, this is a price you will need to pay in order to internationalize your project. You know, most of the blockers are international, not regional.

Yesterday I was able by my own, to allow "com.br" into DnsServer. However, I preferred to ask you, because I didn't want to allow "com.br" (or whatever) but at the price of loosing the blocking ad-tracker-etc capabilities. So now and following your tutorial, I hope that by adding BR to allowed zones, this still will allow the ad-tracker-etc blocking capabilities for BR' domains.

By the way, www.reddit.com and www.facebook.com both also are totally blocked in your project. Many international webpages are blocked, and I will report them to you at the end of our test. But considering that our test is a real-life test, and users need reddit and facebook, please help me to allow these domains (without loosing ad-tracker-etc capabilities).

Thanks! : )

PS1: I don't know if it will be possible, but it will great to separate your blocking-list in categories, so in the future users might choose if they want to use all your blocking-lists, or just the ads-list, just trackers-list, just etc.

PS2: If you allow me a personal opinion, for your project, I believe that ads and trackers blocking-lists is enough. If users want something else (malwares, social media, anti-miners etc), they can add other external lists. In my opinion, if you have a great international ads-trackers-blocking-list + DnsServer = this will be a great project!

**Comment by hl2guide** [comment]
okay, I'll mull over all that and make some variants in about 4 days.

**Comment by hl2guide** [comment]
The first international test blocklist is up at:
https://raw.githubusercontent.com/hl2guide/DNS-Sinkhole-Lists-A2/master/VARIANTS/0_combined_blocklist_international.txt

A variant that does not block social media is also in the works.

**Comment by hl2guide** [comment]
Please continue future discussion at: https://github.com/hl2guide/DNS-Sinkhole-Lists-A2/issues/1
