### ISSUE TITLE
Twitch.tv Third-Party Extensions Breakage.

### ISSUE THREAD

**Issue by DestroyTargetNo** [hl2guide/All-in-One-Customized-Adblock-List#62]
Hello dear,

The BetterTTV and FrankerFaceZ extensions fail to load due to a ",_badfilter_" from the PressTheAttack filterlist.

This issue can be easily resolved by changing the line bellow from:

||twitch.tv^$important,csp=default-src 'self' 'unsafe-inline' 'unsafe-eval' wss: blob: *.jtvnw.net *.ttvnw.net *.twitchcdn.net *.twitch.tv *.facebook.com *.facebook.net recaptcha.net *.google.com *.gstatic.com *.algolia.net;

to:

||twitch.tv^$important,csp=default-src 'self' 'unsafe-inline' 'unsafe-eval' wss: blob: *.jtvnw.net *.ttvnw.net *.twitchcdn.net *.twitch.tv *.facebook.com *.facebook.net recaptcha.net *.google.com *.gstatic.com *.algolia.net *.betterttv.net *.ffzap.com *.frankerfacez.com *.maxcdn.com;

Thank you kindly!

**Comment by hl2guide** [comment]
Thanks for reporting this, I'll look into fixing it in the next major release.

**Comment by DestroyTargetNo** [comment]
Well, nevermind then.. haha
https://github.com/bogachenko/presstheattack/commit/3362983226b4fea095ee8ead22bd3b8e4148b13b
