### ISSUE TITLE
[✗] Format: Adblock (list type not supported)

### ISSUE THREAD

**Issue by antonbek89** [hl2guide/All-in-One-Customized-Adblock-List#64]
Hi
I used Pi-hole  version
Pi-hole Version v4.3.2 Web Interface Version v4.3.2 FTL Version v4.3.1

Added this link :
https://bit.ly/AIO-adblock
or
https://raw.githubusercontent.com/hl2guide/All-in-One-Customized-Adblock-List/master/deanoman-adblocklist.txt

and get error

how fix it ?

**Comment by hl2guide** [comment]
This is a filter list for use in an adblocker like uBlock, not PiHole.

Please keep an eye on my side project that is in alpha: https://github.com/hl2guide/DNS-Sinkhole-Lists-A2
