### ISSUE TITLE
Fail to load

### ISSUE THREAD

**Issue by shafwan7** [hl2guide/All-in-One-Customized-Adblock-List#66]
Google Product fail to reload / access. keep loading all the way seems like no internet access on Google Prouct (youtube, Docs, Keep and many more)
If disable AdBlock Plus, everything load normally.
any fix ? TQ

**Comment by hl2guide** [comment]
For Google it's blocked by default in this list, simply whitelist the adblocking on pages you need to use.

e.g. accounts.google.com
