### ISSUE TITLE
Add merge

### ISSUE THREAD

**Issue by edentc** [hl2guide/All-in-One-Customized-Adblock-List#67]
Hi,
Could you please merge these several?thank you!
https://filters.adtidy.org/extension/chromium/filters/11.txt
https://280blocker.net/files/280blocker_adblock.txt
https://easylist-downloads.adblockplus.org/easylistchina.txt
https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt
http://tools.yiclear.com/ChinaList2.0.txt
http://sub.adtchrome.com/adt-chinalist-easylist.txt

**Comment by hl2guide** [comment]
I'll look these over the next few days, thanks for suggesting them 👍

**Comment by hl2guide** [comment]
I've looked these over and quite a few of them are Chinese filters that I won't include in the AIO list.

The AIO list is already quite large and I'm endeavouring to slim it down.

The others I'll consider for a future version. Thanks  👍
