### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 2020e** [hl2guide/All-in-One-Customized-Adblock-List#69]
Hi,

||connect.facebook.com^$third-party,domain=~facebook.net|~fb.com
||connect.facebook.net
||connect.facebook.net/en_US/fbadnw*-tag.js^
||connect.facebook.net/en_US/fbadnw.js^
||connect.facebook.net/en_US/sdk/xfbml.customerchat.js
||connect.facebook.net/signals/$third-party
||connect.facebook.net^$3p,important
||connect.facebook.net^$important,script
||connect.facebook.net^$third-party,domain=~facebook.com|~fb.com
||connect.facebook.net^*/fbds.js$third-party
||connect.facebook.net^*/fbevents.js$third-party

Can you remove them?
Because his comment area cannot be displayed normally.

**Comment by hl2guide** [comment]
I've decided that the 2020 Beta will be one single list that does block many social media sites.
