### ISSUE TITLE
Code error

### ISSUE THREAD

**Issue by shelbae** [hl2guide/All-in-One-Customized-Adblock-List#70]
There is an emoji in the aio.txt file that causes it to not be able to be added to adblocker filter lists on iOS.

**Comment by hl2guide** [comment]
Is the emoji you're talking about the heart one?
e.g.
![example](https://user-images.githubusercontent.com/17044982/74614234-56087700-516a-11ea-9d57-43758322d554.png)

If so that's a generic emoji that iOS should support.

What adblocker are you using?
Are you using MacOS? If so what version?

**Comment by hl2guide** [comment]
no reply received.
