### ISSUE TITLE
Youtube sidebar

### ISSUE THREAD

**Issue by stefanw1337** [hl2guide/All-in-One-Customized-Adblock-List#71]
So this is blocking the entire sidebar in Youtube, you know the left one with all the menu choices? I need that back. The Notification menu doesn't work either.

And I've tried to go into the logs and see where it gets blocked, because it shows up for like a second before being blocked. But I can't figure it out. Please solve this issue! :)

Edit: I think it's this that does it:
https://i.imgur.com/PYEoYh0.jpg

Even if I add:
@@||www.youtube.com/csi_204$domain=www.youtube.com

It will still block it, and I've tried everything. Help.

**Comment by hl2guide** [comment]
Please consider this list as aggressive and a lock-down of the sidebar and notification menu.

If you need these please consider simply toggling it or off when you need it (if your privacy concerns are more lax than mine).
