### ISSUE TITLE
add Skeletal-Blocker list

### ISSUE THREAD

**Issue by KonoromiHimaries** [hl2guide/All-in-One-Customized-Adblock-List#8]
https://github.com/SkeletalDemise/Skeletal-Blocker

**Comment by hl2guide** [comment]
thanks for the suggestion. I'm internally testing version 2.1 of the list and will strongly consider adding this list to 2.1. Version 2.1 is about 1 week away, if all goes to plan 💃

**Comment by hl2guide** [comment]
Added in version 2.1.

**Comment by SkeletalDemise** [comment]
Hello. I just found this, due to me being on a one month hiatus. Thanks for adding my list to your collection of filter lists. Although just to let you know, most of my filters use uBlock Origin's extended syntax, so Adblock Plus/any other adblocker users won't really benefit much from it.
